name: Test

on:
  push:
    branches:
      - main  # Specify the branch

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run my custom action
        uses: ./
        with:
          person: 'Alice'  # You can omit this to use the default value
